import { saveBase64Image } from './uploadController.js';
import db from '../config/database.js';

const publicImage = (value) => { const v = String(value || ''); return v.startsWith('http://') || v.startsWith('https://') || v.startsWith('data:') || v.startsWith('/') ? v : `/uploads/${v}`; };
const normalize = (row) => ({ id: row.blog_id, title: row.title, category: row.category, date: new Date(row.published_at).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'}), image: publicImage(row.image_url), excerpt: row.excerpt, content: String(row.content || '').split('\n\n'), source: row.source || 'Video Belajar Editorial' });

export const getBlogs = async (req,res,next) => { try { const [rows] = await db.query('SELECT * FROM blog_posts ORDER BY published_at DESC, blog_id DESC'); res.json({success:true,data:rows.map(normalize)}); } catch(e){next(e);} };
export const getBlogById = async (req,res,next) => { try { const [rows] = await db.query('SELECT * FROM blog_posts WHERE blog_id=?',[req.params.id]); if(!rows.length)return res.status(404).json({success:false,message:'Berita tidak ditemukan'}); res.json({success:true,data:normalize(rows[0])}); } catch(e){next(e);} };
export const createBlog = async (req,res,next) => { try { const {title,category='Pendidikan',date,image,imageData,imageName,excerpt='',content=[],source='Video Belajar Editorial'}=req.body; if(!title?.trim())return res.status(400).json({success:false,message:'Judul berita wajib diisi'}); const dateValue = new Date(date || Date.now()); const savedImage = imageData ? await saveBase64Image(imageData, imageName, 'blogs') : (image || ''); const [r]=await db.query('INSERT INTO blog_posts(title,category,published_at,image_url,excerpt,content,source) VALUES(?,?,?,?,?,?,?)',[title,category,dateValue,savedImage,excerpt,Array.isArray(content)?content.join('\n\n'):content,source]); const [rows]=await db.query('SELECT * FROM blog_posts WHERE blog_id=?',[r.insertId]); res.status(201).json({success:true,data:normalize(rows[0])}); }catch(e){next(e);} };
export const updateBlog = async (req,res,next) => { try { const {title,category,date,image,imageData,imageName,excerpt='',content=[],source}=req.body; const savedImage = imageData ? await saveBase64Image(imageData, imageName, 'blogs') : (image || ''); await db.query('UPDATE blog_posts SET title=?,category=?,published_at=?,image_url=?,excerpt=?,content=?,source=? WHERE blog_id=?',[title,category,new Date(date),savedImage,excerpt,Array.isArray(content)?content.join('\n\n'):content,source||'Video Belajar Editorial',req.params.id]); const [rows]=await db.query('SELECT * FROM blog_posts WHERE blog_id=?',[req.params.id]); if(!rows.length)return res.status(404).json({success:false,message:'Berita tidak ditemukan'}); res.json({success:true,data:normalize(rows[0])}); }catch(e){next(e);} };
export const deleteBlog = async (req,res,next) => { try { const [r]=await db.query('DELETE FROM blog_posts WHERE blog_id=?',[req.params.id]); if(!r.affectedRows)return res.status(404).json({success:false,message:'Berita tidak ditemukan'}); res.json({success:true,message:'Berita berhasil dihapus'}); }catch(e){next(e);} };
