import { Router } from "express";
import { getCourses, getCourseById, getCourseBySlug, createCourse, updateCourse, deleteCourse } from "../controllers/courseController.js";
import { authenticate, requireRole } from "../middleware/authMiddleware.js";
const router = Router();
router.get("/", getCourses);
router.get("/slug/:slug", getCourseBySlug);
router.get("/:id", getCourseById);
router.post("/", authenticate, requireRole("admin", "superadmin"), createCourse);
router.put("/:id", authenticate, requireRole("admin", "superadmin"), updateCourse);
router.delete("/:id", authenticate, requireRole("admin", "superadmin"), deleteCourse);
export default router;
