import { Router } from 'express';
import { getCourses,getCourseById,getCourseBySlug,createCourse,updateCourse,deleteCourse } from '../controllers/courseController.js';
const router = Router();
router.get('/', getCourses);
router.get('/slug/:slug', getCourseBySlug);
router.get('/:id', getCourseById);
router.post('/', createCourse);
router.put('/:id', updateCourse);
router.delete('/:id', deleteCourse);
export default router;
