import { useState } from "react";
import { Link } from "react-router-dom";
import { FiBookOpen, FiClock, FiDownload, FiFileText, FiSearch, FiStar } from "react-icons/fi";
import { readPayments } from "../services/payment";
import { useAuth } from "../context/AuthContext";
import { useCourses } from "../context/CourseContext";
import { canDownloadCertificate, downloadCertificate, progressFromLearning, readLearning } from "../utils/learning";

export default function MyCourses() {
  const { user } = useAuth(); const { courses } = useCourses();
  const [query, setQuery] = useState(""); const [tab, setTab] = useState("Semua Kelas");
  const paid = readPayments(user?.email).filter(p => p.status === "paid");
  const items = paid.map(payment => ({ payment, course: courses.find(c => String(c.id) === String(payment.courseId)) || { id:payment.courseId,title:payment.title,thumbnail:payment.thumbnail,description:"Kelas pembelajaran Video Belajar",duration_hours:0 } })).filter(({course}) => course.title.toLowerCase().includes(query.toLowerCase())).map(item => ({...item, learning:readLearning(user?.email,item.course.id)}));
  const filtered = items.filter(({learning}) => tab === "Semua Kelas" || (tab === "Selesai" ? progressFromLearning(learning)>=100 : progressFromLearning(learning)<100));
  return <main className="min-h-screen bg-[#fffdf4] px-3 py-4 sm:px-0"><div className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm sm:p-6">
    <div className="flex flex-col gap-4 border-b border-gray-200 pb-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-5 text-sm font-semibold">{["Semua Kelas","Sedang Berjalan","Selesai"].map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?"border-b-2 border-orange-400 pb-3 text-orange-500":"pb-3 text-gray-400"}>{item}</button>)}</div><label className="flex h-10 w-full items-center gap-2 rounded-lg border border-gray-200 px-3 lg:w-64"><FiSearch className="text-gray-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari Kelas" className="min-w-0 flex-1 outline-none text-sm"/></label></div>
    {filtered.length===0 ? <div className="py-16 text-center"><FiBookOpen className="mx-auto text-5xl text-gray-300"/><h2 className="mt-4 font-bold">Belum ada kelas</h2><p className="mt-1 text-sm text-gray-500">Kelas yang sudah dibayar akan muncul di sini.</p><Link to="/courses" className="mt-5 inline-flex rounded-xl bg-green-500 px-5 py-3 text-sm font-bold text-white">Cari Kelas</Link></div> : <div className="mt-6 space-y-5">{filtered.map(({course,learning})=>{ const progress=progressFromLearning(learning); const eligible=canDownloadCertificate(learning); return <article key={course.id} className="overflow-hidden rounded-2xl border border-gray-200"><div className="flex flex-wrap items-center justify-between gap-3 bg-[#f9fff7] px-4 py-3 text-sm"><span><b>{learning.completedItems.length}</b> / 12 Modul Terselesaikan</span><span className={`rounded-lg px-3 py-1 text-xs font-bold ${progress>=100?"bg-green-100 text-green-600":"bg-orange-50 text-orange-500"}`}>{progress>=100?"Selesai":"Sedang Berjalan"}</span></div><div className="grid gap-4 p-4 sm:grid-cols-[180px_1fr] sm:p-5"><img src={course.thumbnail} alt={course.title} className="h-36 w-full rounded-xl object-cover sm:h-32"/><div><h3 className="text-lg font-bold">{course.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-gray-500">{course.description}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-gray-500"><span className="inline-flex items-center gap-1"><FiFileText/>12 Modul</span><span className="inline-flex items-center gap-1"><FiClock/>{course.duration_hours || 8} Jam</span></div><div className="mt-4 flex items-center gap-3"><span className="whitespace-nowrap text-xs text-gray-500">Progres Kelas: <b>{progress}%</b></span><div className="h-2 flex-1 rounded-full bg-gray-100"><div className="h-full rounded-full bg-green-500 transition-all" style={{width:`${progress}%`}}/></div></div></div></div><div className="flex flex-col gap-3 border-t bg-[#f9fff7] px-4 py-3 sm:flex-row sm:items-center sm:justify-end"><Link to={`/learn/${course.id}`} className="rounded-xl bg-green-500 px-5 py-2.5 text-center text-sm font-bold text-white">Lihat Detail Kelas</Link>{eligible && <button onClick={()=>downloadCertificate(course,user,learning.finalScore)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-green-500 px-5 py-2.5 text-sm font-bold text-green-600"><FiDownload/> Unduh Sertifikat</button>}{learning.review && <span className="inline-flex items-center gap-1 text-xs text-gray-500"><FiStar className="fill-yellow-400 text-yellow-400"/> {learning.review.rating}/5</span>}</div></article>})}</div>}
  </div></main>;
}
