-- VideoBelajar - Supabase PostgreSQL schema
-- Jalankan di Supabase SQL Editor.
-- File ini tidak membuat database; Supabase sudah menyediakan database postgres.

CREATE TABLE IF NOT EXISTS categories (
  category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL,
  category_slug VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  icon_url VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_categories_name ON categories(category_name);

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'student',
  phone_number VARCHAR(20),
  avatar_url VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email_verified_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);

CREATE TABLE IF NOT EXISTS courses (
  course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instructor_id BIGINT NOT NULL REFERENCES users(user_id),
  category_id BIGINT NOT NULL REFERENCES categories(category_id),
  course_title VARCHAR(255) NOT NULL,
  course_slug VARCHAR(255) NOT NULL UNIQUE,
  thumbnail_url TEXT NOT NULL,
  promo_video_url VARCHAR(255),
  level VARCHAR(20) NOT NULL DEFAULT 'beginner' CHECK (level IN ('beginner','intermediate','advanced')),
  duration_hours INTEGER NOT NULL DEFAULT 0 CHECK (duration_hours >= 0),
  description TEXT NOT NULL,
  total_students INTEGER NOT NULL DEFAULT 0 CHECK (total_students >= 0),
  average_rating NUMERIC(3,2) NOT NULL DEFAULT 0.00 CHECK (average_rating >= 0 AND average_rating <= 5),
  price NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (price >= 0),
  discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0.00 CHECK (discount_percent >= 0 AND discount_percent <= 100),
  discount_start_date DATE,
  discount_end_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_courses_instructor ON courses(instructor_id);
CREATE INDEX IF NOT EXISTS idx_courses_category_level ON courses(category_id, level);
CREATE INDEX IF NOT EXISTS idx_courses_duration ON courses(duration_hours);
CREATE INDEX IF NOT EXISTS idx_courses_discount_dates ON courses(discount_start_date, discount_end_date);

CREATE TABLE IF NOT EXISTS enrollments (
  enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  course_id BIGINT NOT NULL REFERENCES courses(course_id),
  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  progress_percentage NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  CONSTRAINT uq_enrollments_user_course UNIQUE(user_id, course_id)
);
CREATE INDEX IF NOT EXISTS idx_enrollments_course ON enrollments(course_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_user_completed ON enrollments(user_id,is_completed);

CREATE TABLE IF NOT EXISTS videos (
  video_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  order_index INTEGER NOT NULL,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  video_url VARCHAR(255) NOT NULL,
  is_preview BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_videos_course_order UNIQUE(course_id, order_index)
);
CREATE INDEX IF NOT EXISTS idx_videos_course_order ON videos(course_id,order_index);

CREATE TABLE IF NOT EXISTS questions (
  question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  question_type VARCHAR(30) NOT NULL DEFAULT 'multiple_choice' CHECK (question_type IN ('multiple_choice','true_false')),
  points INTEGER NOT NULL DEFAULT 10 CHECK (points >= 0),
  phase VARCHAR(20) NOT NULL DEFAULT 'quiz' CHECK (phase IN ('pretest','quiz','final')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_questions_course_type ON questions(course_id,question_type);
CREATE INDEX IF NOT EXISTS idx_questions_course_phase ON questions(course_id,phase);

CREATE TABLE IF NOT EXISTS question_options (
  option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,
  option_text VARCHAR(255) NOT NULL,
  is_correct BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_question_options_question_correct ON question_options(question_id,is_correct);

CREATE TABLE IF NOT EXISTS question_answers (
  answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id BIGINT NOT NULL REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
  question_id BIGINT NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,
  option_id BIGINT NOT NULL REFERENCES question_options(option_id) ON DELETE CASCADE,
  is_correct BOOLEAN NOT NULL DEFAULT FALSE,
  answered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_question_answers_enrollment_question UNIQUE(enrollment_id,question_id)
);
CREATE INDEX IF NOT EXISTS idx_question_answers_question_option ON question_answers(question_id,option_id);
CREATE INDEX IF NOT EXISTS idx_question_answers_enrollment ON question_answers(enrollment_id);

CREATE TABLE IF NOT EXISTS reviews (
  review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  course_id BIGINT NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_reviews_user_course UNIQUE(user_id,course_id)
);
CREATE INDEX IF NOT EXISTS idx_reviews_course_rating ON reviews(course_id,rating);

CREATE TABLE IF NOT EXISTS orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  order_number VARCHAR(50) NOT NULL UNIQUE,
  total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','completed','expired')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders(user_id,status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);

CREATE TABLE IF NOT EXISTS order_items (
  order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(course_id),
  price_at_purchase NUMERIC(12,2) NOT NULL CHECK (price_at_purchase >= 0),
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (discount_amount >= 0),
  CONSTRAINT uq_order_items_order_course UNIQUE(order_id,course_id)
);
CREATE INDEX IF NOT EXISTS idx_order_items_course ON order_items(course_id);

CREATE TABLE IF NOT EXISTS payment_methods (
  payment_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  method_name VARCHAR(100) NOT NULL,
  provider_code VARCHAR(50) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  icon_url VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS idx_payment_methods_active ON payment_methods(is_active);

CREATE TABLE IF NOT EXISTS payments (
  payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  payment_method_id BIGINT NOT NULL REFERENCES payment_methods(payment_method_id),
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending','success','failed')),
  transaction_id VARCHAR(100) UNIQUE,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payments_order_status ON payments(order_id,payment_status);
CREATE INDEX IF NOT EXISTS idx_payments_method ON payments(payment_method_id);

CREATE TABLE IF NOT EXISTS certificates (
  certificate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id BIGINT NOT NULL UNIQUE REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
  certificate_url VARCHAR(255) NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  certificate_code VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS video_progress (
  video_progress_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id BIGINT NOT NULL REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
  video_id BIGINT NOT NULL REFERENCES videos(video_id) ON DELETE CASCADE,
  is_completed BOOLEAN NOT NULL DEFAULT FALSE,
  last_watched_at TIMESTAMPTZ,
  CONSTRAINT uq_video_progress_enrollment_video UNIQUE(enrollment_id,video_id)
);
CREATE INDEX IF NOT EXISTS idx_video_progress_video ON video_progress(video_id);

CREATE TABLE IF NOT EXISTS blog_posts (
  blog_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL UNIQUE,
  category VARCHAR(100) NOT NULL DEFAULT 'Pendidikan',
  published_at DATE NOT NULL,
  image_url TEXT,
  excerpt TEXT,
  content TEXT NOT NULL,
  source VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_blog_published ON blog_posts(published_at);
CREATE INDEX IF NOT EXISTS idx_blog_category ON blog_posts(category);

-- Seed minimal payment methods. Data kursus dapat diimpor dari CSV setelah schema dibuat.
INSERT INTO payment_methods (method_name, provider_code, is_active) VALUES
  ('Bank BCA','Bank BCA',TRUE),
  ('Bank BNI','Bank BNI',TRUE),
  ('Bank BRI','Bank BRI',TRUE),
  ('Bank Mandiri','Bank Mandiri',TRUE),
  ('Dana','Dana',TRUE),
  ('OVO','OVO',TRUE),
  ('LinkAja','LinkAja',TRUE),
  ('Shopee Pay','Shopee Pay',TRUE),
  ('Kartu Kredit/Debit','card',TRUE)
ON CONFLICT (provider_code) DO UPDATE
SET method_name = EXCLUDED.method_name,
    is_active = EXCLUDED.is_active;
